/* eslint-disable prettier/prettier */
export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const EMPLOYEE_REPOSITORY = 'EMPLOYEE_REPOSITORY';
export const DEPARTMENT_REPOSITORY = 'DEPARTMENT_REPOSITORY';
export const TITLE_REPOSITORY ='TITLE_REPOSITORY';
export const SALARY_REPOSITORY = 'SALARY_REPOSITORY';
export const DEPARTMENT_MANAGER_REPOSITORY = 'DEPARTMENT_MANAGER_REPOSITORY';
export const EMPLOYEE_PROFILE_REPOSITORY = 'EMPLOYEE_PROFILE_REPOSITORY';